### ISSUE TITLE
Excess Flood on IRC when gitter users paste away

### ISSUE THREAD

**Issue by caktux** [finnp/gitter-irc-bot#12]
Some rate limiting / flood protection would be great, or even better, detect code blocks and publish them as gists

**Comment by finnp** [comment]
Good point. It should also recognize newlines and maybe for if they are `<=5` lines, send it to irc prefixed with the username for each lines and if it's `>5` cut it off and link the original message.

It is possible to link gitter messages like this: https://gitter.im/finnp/gitter-irc-bot?at=557ac9be813c577e1cf62341,

**Comment by finnp** [comment]
@caktux As of version v1.3.0 the bot now prevents flooding. If a message is longer than 4 lines, it will shorten it and add a link to the original message.

**Comment by caktux** [comment]
nice, many thanks, will take this for a spin :)
