### ISSUE TITLE
Bot sometimes stops forwarding from gitter to irc

### ISSUE THREAD

**Issue by jck** [finnp/gitter-irc-bot#16]
I'm not sure what causes this, but after leaving the bot on, it eventually stops seeing and forwarding gitter messages. It still does irc->gitter forwarding. Restarting the bot fixes the issue.

**Comment by finnp** [comment]
Is your bot running on Heroku?

**Comment by ForNeVeR** [comment]
@finnp I could say that _my_ bot is running on Heroku for about 6 months now (I am using code from commit 08b466488f7f8ccfa1f41feed980d22372b2bf9e), and it doesn't require any restarts. Your bootstrapping mechanism works nicely.

**Comment by finnp** [comment]
@ForNeVeR Thanks for the input! The thing is I have a bot running on heroku as well and it has problems too. Maybe I introduced a bug after 1.2.0... Are you sure forwarding from gitter to irc works for you?

**Comment by ForNeVeR** [comment]
Yes I am sure that everything works, and it uses exactly the commit I mentioned. So, really, it maybe the problem with some of the latest commits.

**Comment by feross** [comment]
I am running a bot and experience the same issue. Forwarding from gitter -> irc stops working after a while, while the reverse keeps working just fine.

Hosting on Linode. (#webtorrent on freenode & http://gitter.im/feross/webtorrent)

**Comment by finnp** [comment]
Okay I have a new version on master, which uses the faye endpoint from gitter. If you want you can deploy from master and see if it fixes it. I am going to run this a few days and if there are no issues I am going to publish it to npm.

**Comment by feross** [comment]
Cool!

**Comment by finnp** [comment]
Should be fixed in 1.5.0. If this happens again, please open another issue and let me know.
