### ISSUE TITLE
message from API tokjen owner are not going Gitter > IRC.

### ISSUE THREAD

**Issue by lagleki** [finnp/gitter-irc-bot#25]
I used API token from my account and it appears that everything I say in Gitter is not coming to IRC.

For other users there is not such problem.
For messages IRC to Gitter there is not such problem for anyone either.

Of course, I can create a fresh account that nobody will use but it'd be kinda strange.

**Comment by finnp** [comment]
Exactly. The API token shouldn't be for your personal GitHub account, but for a designated GitHub bot account.
