### ISSUE TITLE
bot leaves freenode then rejoins after next gitter message

### ISSUE THREAD

**Issue by ahgittin** [finnp/gitter-irc-bot#3]
We've been running this for a few days between freenode and gitter.im.  We notice that after a time it seems the bot leaves the freenode room ("timeout" reported by freenode irc), and thereafter doesn't pick up messages from that room.  (There is no record of new messages in the log file.)

If you then write a message from the gitter side the bot *does* notice and it appears in the log, but it is not written at the freenode side.  Several seconds later the bot reconnects on the freenode side and after that messages are mirrored normally again.

So it seems like there is a drop-off with no reconnection event until after a failed write, maybe?

**Comment by finnp** [comment]
Seems weird to me as I didn't have these issues. The bot should try to reconnect automatically on a disconnect and also prevent timeouts. That's all handled by the `irc` module.

Does this happen often?

**Comment by ahgittin** [comment]
it's happened twice in one week.  probably something weird with the network in the cloud where it's running.

if it keeps happening i'll add some debug statements to the irc module.  thanks.

**Comment by finnp** [comment]
I think this could also be solved by just removing the `retryCount` option here: https://github.com/finnp/gitter-irc-bot/blob/master/index.js#L14. So it would try to reconnect forever (every 2 seconds).
