### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by awrelll** [finnp/gitter-irc-bot#7]
hello,
i'm using this bridge but it seems that messages from gitter don't get synced to IRC channel.
Any ideas why ?
Thanks !

**Comment by finnp** [comment]
You have written me an email as well. Have you figures out how to set the environment variables correctly?

**Comment by awrelll** [comment]
yeah, solved it! Thanks anyway!

**Comment by finnp** [comment]
Cool \o/

**Comment by awrelll** [comment]
is there a way to keep it running even if you close the console ?  i tryed forever but ```npm start``` says ```
> gitter-irc-bot@1.1.1 start /root/gitter-irc-bot
> ./bin.js


module.js:340
    throw err;
          ^
Error: Cannot find module 'irc'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/gitter-irc-bot/index.js:1:73)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

npm ERR! gitter-irc-bot@1.1.1 start: `./bin.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the gitter-irc-bot@1.1.1 start script.
npm ERR! This is most likely a problem with the gitter-irc-bot package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./bin.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls gitter-irc-bot
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.19.0-15-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! cwd /root/gitter-irc-bot
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /root/gitter-irc-bot/npm-debug.log
npm ERR! not ok code 0
```

Thanks in advance!

**Comment by finnp** [comment]
try `nohup npm start &`

**Comment by awrelll** [comment]
same error ```with nohup npm start &
what should i do?

**Comment by finnp** [comment]
Then try `nohup gitter-irc-bot &`

**Comment by awrelll** [comment]
it works great now!!!! Thanks!!! Can the bot be also set to respond some predifined questions or am I a dreamer ? :+1:

**Comment by finnp** [comment]
Great. Nope, you'd need another bot for that.

**Comment by awrelll** [comment]
Thanks!
